modLoader="javafml" #mandatory
loaderVersion="[24,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="erbymodpack" #mandatory
version="0.1" #mandatory
displayName="ErBy ModPack" #mandatory
credits="Thanks for the tutorials Harry Talks" #optional
authors="ErWaNErBy" #optional
description='''
Un mod d'entrainement pour la version :
1.13.2 de Minecraft
'''
[[dependencies.erbymodpack]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.erbymodpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"